publish_mode: editorial_workflow
backend:
  name: github
  repo: tanho63/tanho.ca
  branch: main
  squash_merges: true
media_folder: /static/images
public_folder: /public
collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    path: '{{slug}/index'
    sortable_fields: ['date', 'title', 'publish_date']
    media_folder: ''
    public_folder: ''
    nested:
      depth: 100
      summary: '{{title}}'
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    editor:
      preview: false
    fields:
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list'}
      - { label: 'URL', name: 'url', widget: 'string'}
      - { label: 'Aliases', name: 'aliases', widget: 'list'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
